package com.androidexpert35.audiophilemusicplayer.di

import android.content.ContentResolver
import android.content.Context
import android.content.SharedPreferences
import android.hardware.usb.UsbManager
import android.media.AudioManager
import androidx.room.Room
import com.androidexpert35.audiophilemusicplayer.data.local.AudiophileDatabase
import com.androidexpert35.audiophilemusicplayer.data.local.dao.LibraryIndexDao
import com.androidexpert35.audiophilemusicplayer.data.local.dao.LikedSongDao
import com.androidexpert35.audiophilemusicplayer.data.local.dao.LyricsCacheDao
import com.androidexpert35.audiophilemusicplayer.data.local.dao.PlaybackStateDao
import com.androidexpert35.audiophilemusicplayer.data.local.dao.RecentlyPlayedDao
import com.androidexpert35.audiophilemusicplayer.data.repository.SettingsPreferences
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import javax.inject.Singleton

/**
 * Application-scoped Hilt module providing fundamental Android dependencies
 * and coroutine dispatchers.
 */
@Module
@InstallIn(SingletonComponent::class)
object AppModule {

    /**
     * Provides the system [ContentResolver] for MediaStore queries.
     *
     * @param context Application context.
     * @return The application's [ContentResolver].
     */
    @Provides
    @Singleton
    fun provideContentResolver(
        @ApplicationContext context: Context
    ): ContentResolver = context.contentResolver

    /**
     * Provides the app's dedicated settings [SharedPreferences] instance.
     */
    @Provides
    @Singleton
    fun provideSharedPreferences(
        @ApplicationContext context: Context
    ): SharedPreferences = context.getSharedPreferences(
        SettingsPreferences.PREFS_NAME,
        Context.MODE_PRIVATE,
    )

    /**
     * Provides the system [UsbManager] for direct USB DAC discovery and I/O.
     */
    @Provides
    @Singleton
    fun provideUsbManager(
        @ApplicationContext context: Context
    ): UsbManager = context.getSystemService(Context.USB_SERVICE) as UsbManager

    /** Provides the system [AudioManager] for playback routing infrastructure. */
    @Provides
    @Singleton
    fun provideAudioManager(
        @ApplicationContext context: Context
    ): AudioManager = context.getSystemService(AudioManager::class.java)

    /**
     * Provides the Room database that caches the indexed local library.
     *
     * @param context Application context used to open the database file.
     * @return Singleton [AudiophileDatabase] instance.
     */
    @Provides
    @Singleton
    fun provideAudiophileDatabase(
        @ApplicationContext context: Context
    ): AudiophileDatabase = Room.databaseBuilder(
        context,
        AudiophileDatabase::class.java,
        AudiophileDatabase.DATABASE_NAME
    )
        .addMigrations(
            AudiophileDatabase.MIGRATION_1_2,
            AudiophileDatabase.MIGRATION_2_3,
            AudiophileDatabase.MIGRATION_3_4,
            AudiophileDatabase.MIGRATION_4_5,
            AudiophileDatabase.MIGRATION_5_6,
            AudiophileDatabase.MIGRATION_6_7,
            AudiophileDatabase.MIGRATION_7_8,
            AudiophileDatabase.MIGRATION_8_9,
        )
        .build()

    /**
     * Provides the DAO used for indexed-library reads and writes.
     *
     * @param database The application Room database.
     * @return [LibraryIndexDao] implementation generated by Room.
     */
    @Provides
    @Singleton
    fun provideLibraryIndexDao(
        database: AudiophileDatabase
    ): LibraryIndexDao = database.libraryIndexDao()

    /**
     * Provides the DAO for reading and writing the singleton playback-session row.
     *
     * @param database The application Room database.
     * @return [PlaybackStateDao] implementation generated by Room.
     */
    @Provides
    @Singleton
    fun providePlaybackStateDao(
        database: AudiophileDatabase
    ): PlaybackStateDao = database.playbackStateDao()

    /**
     * Provides the DAO for reading and writing the liked-songs collection.
     *
     * @param database The application Room database.
     * @return [LikedSongDao] implementation generated by Room.
     */
    @Provides
    @Singleton
    fun provideLikedSongDao(
        database: AudiophileDatabase
    ): LikedSongDao = database.likedSongDao()

    /**
     * Provides the DAO for reading and writing the recently-played history.
     *
     * @param database The application Room database.
     * @return [RecentlyPlayedDao] implementation generated by Room.
     */
    @Provides
    @Singleton
    fun provideRecentlyPlayedDao(
        database: AudiophileDatabase
    ): RecentlyPlayedDao = database.recentlyPlayedDao()

    /**
     * Provides the DAO for reading and writing the lyrics cache.
     *
     * @param database The application Room database.
     * @return [LyricsCacheDao] implementation generated by Room.
     */
    @Provides
    @Singleton
    fun provideLyricsCacheDao(
        database: AudiophileDatabase
    ): LyricsCacheDao = database.lyricsCacheDao()

    /**
     * Provides the IO dispatcher for blocking I/O operations.
     */
    @Provides
    @IoDispatcher
    fun provideIoDispatcher(): CoroutineDispatcher = Dispatchers.IO

    /**
     * Provides the Main dispatcher for UI-thread operations.
     */
    @Provides
    @MainDispatcher
    fun provideMainDispatcher(): CoroutineDispatcher = Dispatchers.Main

    /**
     * Provides the Default dispatcher for CPU-intensive work.
     */
    @Provides
    @DefaultDispatcher
    fun provideDefaultDispatcher(): CoroutineDispatcher = Dispatchers.Default

    /**
     * Provides a main-thread [CoroutineScope] for long-lived infrastructure
     * that must run on the main thread (e.g. the playback position ticker).
     *
     * Uses a [SupervisorJob] so individual child failures don't cancel
     * sibling coroutines. Qualified with [ApplicationScope] (not [MainDispatcher])
     * to keep the scope and dispatcher bindings unambiguous in the DI graph.
     */
    @Provides
    @Singleton
    @ApplicationScope
    fun provideMainScope(): CoroutineScope =
        CoroutineScope(SupervisorJob() + Dispatchers.Main)
}
